name: kafka-connect-bigquery
lang: java
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_secrets: ["kcbq_gcp"]
